host: localhost
port: 3000
title: "This Is My Cloud Portal"
sortAlphabetically: false
portals:
- title: home
  emoji: ğŸ 
  link: /
  external: false
- title: mails
  emoji: âœ‰ï¸
  link: https://mail.thisismy.cloud
  external: true
- title: dns
  emoji: ğŸŒ
  link: https://dns.thisismy.cloud
  external: true
- title: about
  emoji: â“
  link: /about
  external: false