host: localhost
port: 3000
contextPath: ""
enableMetrics: true
metricsHost: localhost
metricsPort: 3030
title: "portkey"
hideTitle: false
subtitle: "Where do you want to go?"
hideSearchBar: false
headerAddition: |-
  <script defer src="https://analytics.thisismy.cloud/script.js" data-website-id="72fa7b3a-10fa-4273-ae81-d3218b879e06" data-domains="demo.portkey.page"></script>
footer: |-
  <p><a class="no-underline border-b-1 border-solid" target="_blank" rel="nofollow" href="https://www.portkey.page/">portkey</a> made with â˜•ï¸ by <a class="no-underline border-b-1 border-solid" target="_blank" rel="nofollow" href="https://www.codehat.de">CodeHat</a></p>
showTopIcon: true
showKeywordsAsTooltips: true
sortAlphabetically: false
searchWithStringSimilarity: true
minimumStringSimilarity: 0.5
portals:
- title: 1password
  emoji: ğŸ”‘
  link: https://my.1password.eu/
  keywords:
  - passwords
  - vault
  - 2fa
  - totp
- title: gmail
  emoji: âœ‰ï¸
  link: https://mail.google.com
  keywords:
  - emails
- title: x (twitter)
  emoji: ğŸ¦
  link: https://twitter.com
- title: github
  emoji: ğŸ’»
  link: https://github.com/
  keywords:
  - code
  - collaboration
- title: about
  emoji: â“
  link: /about
  keywords:
  - info
- title: version
  emoji: ğŸ”¢
  link: /version
pages:
- heading: "About"
  subtitle: "What is this thing?"
  path: /about
  content: |-
    This website is used to have a collection of <em>links</em> that allow you to quickly head over to different <em>applications</em>.</br>
    </br>
    You can additionally define smaller <em>custom pages</em> in the configuration file.