host: localhost
port: 3000
title: "portkey"
# Remember that Tailwind classes used here only work if already used somewhere else because the bundler couldn't look here!
footer: |-
  <p><a class="no-underline border-b-2 border-solid" target="_blank" rel="nofollow" href="https://www.portkey.page/">portkey</a> made with â˜•ï¸ by <a class="no-underline border-b-2 border-solid" target="_blank" rel="nofollow" href="https://www.codehat.de">CodeHat</a></p>
sortAlphabetically: false
portals:
- title: 1password
  emoji: ğŸ”‘
  link: https://my.1password.eu/
  external: true
  keywords:
  - passwords
  - vault
  - 2fa
  - totp
- title: gmail
  emoji: âœ‰ï¸
  link: https://mail.google.com
  external: true
  keywords:
  - emails
- title: x (twitter)
  emoji: ğŸ¦
  link: https://twitter.com
  external: true
- title: github
  emoji: ğŸ’»
  link: https://github.com/
  external: true
  keywords:
  - code
  - collaboration
- title: about
  emoji: â“
  link: /about
  external: false
  keywords:
  - info
- title: version
  emoji: ğŸ”¢
  link: /version
  external: false
- title: home
  emoji: ğŸ 
  link: /
  external: false
pages:
- heading: "About"
  path: /about
  content: |-
    This website is used to have a collection of <em>links</em> that allow you to quickly head over to different <em>applications</em>.</br>
    </br>
    You can additionally define smaller <em>custom pages</em> in the configuration file.